---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pythonscheduler
spec:
  replicas: 1
  selector:
    app: pythonscheduler
  template:
    metadata:
      name: pythonscheduler
      labels:
        app: pythonscheduler
    spec:
      serviceAccount: sysdig-account
      containers:
      - name: pythonscheduler
        image: <your_image_name>:latest
        volumeMounts:
        - name: sysdigtoken
          mountPath: "/etc/sysdigtoken"
          readOnly: true
      volumes:
      - name: sysdigtoken
        secret:
          secretName: sysdig-token
